# Generated by Django 4.0.4 on 2022-05-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220513_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_name',
            new_name='username',
        ),
    ]
