# Generated by Django 4.0.4 on 2022-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_user_name_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
